version: '3.8'

services:
  chatwoot-pipedrive:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./temp:/app/temp
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHATWOOT_API_TOKEN=${CHATWOOT_API_TOKEN}
      - CHATWOOT_BASE_URL=${CHATWOOT_BASE_URL}
      - PIPEDRIVE_API_TOKEN=${PIPEDRIVE_API_TOKEN}
      - PIPEDRIVE_BASE_URL=${PIPEDRIVE_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
